### ISSUE TITLE
Pathway raster no longer exist

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/cplus-plugin#198]
When running a scenario, the first time runs fine, all outputs are added, and the pathways are fine. When rerunning the pathways QgsRasterLayers are broken in the ScenarioResult. All other results are fine.

Here is the error messages:
![image](https://github.com/kartoza/cplus-plugin/assets/79740955/58ca9a15-06da-4e56-880d-349287ba2464)

To replicate:

- Select pathways for all IMs. Select more than 2 for some cases
- Run it
- Once it finishes, it should all be fine
- Delete the created Scenario folder
- Now rerun the Scenario (make no changes to the Scenario!!!)
- This time the Pathways will cause issues

**Comment by vermeulendivan** [comment]
This should be resolved now by a caching issue John fixed with the pathways

**Comment by gkahiu** [comment]
Addressed in #197.
