### ISSUE TITLE
Finalise automated report

### ISSUE THREAD

**Issue by amyburness** [ConservationInternational/cplus-plugin#257]
The automated report needs some updates: 

- scaling the output maps correctly 
- the final calculations for the cost and carbon (if we decide it include them)
- add information to the implementation model maps like area
- Set character length constraints for description in NCS and IM dialogs so that the corresponding description in the report fits within the available layout label.

**Comment by gkahiu** [comment]
Hi @amyburness , the scaling issue was addressed in PR #222. You can confirm if further changes are required from the plugin repository.

**Comment by gkahiu** [comment]
Addressed in #297
