### ISSUE TITLE
UR 4: Allow users to define financial inputs for each implementation model. User-defined inputs must include Inflation Rate, Implementation Cost/hectare/year, hectares treated/year, Number of years

### ISSUE THREAD

**Issue by amyburness** [ConservationInternational/cplus-plugin#320]
Edit the current workflow in creating priority weighting layer and include an option to select the type of the layer, the type of the layer should include whether it is for "inflation rate", "implementation cost/hectare/year", "hectares treated/year" or "number of years".

For each type corresponding parameters inputs should be enabled and allow user to add/pass values for those parameters.

![image](https://github.com/ConservationInternational/cplus-plugin/assets/77841514/48b7e0e6-e3ca-47ec-83ae-5bde6d5984d4)

**Comment by gkahiu** [comment]
Implemented in #448.
