### ISSUE TITLE
UR 11: Basic data validation (resolution, data types, projection, NoData check) 

### ISSUE THREAD

**Issue by amyburness** [ConservationInternational/cplus-plugin#327]
Basic data validation (resolution, data types, projection, NoData check) 
![image](https://github.com/ConservationInternational/cplus-plugin/assets/77841514/565feb28-057a-4d32-8469-5cb881057b02)

Validation will be undertaken when NCS pathway or implementation model layers are added or modified under Step 2.

**Comment by gkahiu** [comment]
Implemented in #383.
