### ISSUE TITLE
UR 1: Basic name changes for “implementation model” and other new terms in the plugin

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/cplus-plugin#332]
Update user documentation to contain the new changes for the "implementation model" and the new items in the plugin.

Original implementation issue https://github.com/ConservationInternational/cplus-plugin/issues/317.

![image](https://github.com/ConservationInternational/cplus-plugin/assets/77841514/5b77561e-bdbb-4b26-9883-dcb2ca689cad)

**Comment by gkahiu** [comment]
Addressed in #368.
