### ISSUE TITLE
UR 4: Allow users to define financial inputs for each implementation model. User-defined inputs must include Inflation Rate, Implementation Cost/hectare/year, hectares treated/year, Number of years

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/cplus-plugin#340]
Update the priority weighting layer plugin API to include the new layers types.

Document the new priority weighting layer creation workflow that includes the new types of layers.

Original implementation issue -https://github.com/ConservationInternational/cplus-plugin/issues/320

![image](https://github.com/ConservationInternational/cplus-plugin/assets/77841514/48b7e0e6-e3ca-47ec-83ae-5bde6d5984d4)

**Comment by gkahiu** [comment]
Implemented in #448.
