### ISSUE TITLE
UR 5a: Modify report settings for additional text entry field

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/cplus-plugin#342]
Include the new report fields in the plugin API documentation.

Original implementation issue - https://github.com/ConservationInternational/cplus-plugin/issues/321

![image](https://github.com/ConservationInternational/cplus-plugin/assets/77841514/6d3b7655-3032-4cb2-a11c-d7072852d4e5)

**Comment by gkahiu** [comment]
Addressed in #354.
