### ISSUE TITLE
CPLUS API: Remove local file path from Scenario JSON

### ISSUE THREAD

**Issue by zamuzakki** [ConservationInternational/cplus-plugin#446]
Make  these paths from Scenario JSON an empty string

![Image](https://github.com/ConservationInternational/cplus-plugin/assets/7352963/3eb8ee9c-9668-4c12-aae3-54fc351dc54b)

![Image](https://github.com/ConservationInternational/cplus-plugin/assets/7352963/5a8744c7-b6b9-4c49-aceb-5bb38bb4758f)

**Comment by danangmassandy** [comment]
Implemented via https://github.com/danangmassandy/cplus-plugin/pull/17
