### ISSUE TITLE
Cplus Plugin: Check Installation issue

### ISSUE THREAD

**Issue by zamuzakki** [ConservationInternational/cplus-plugin#464]
Check installation issue experienced by @amyburness . I have also tested installing plugin in fresh machine, and got same issue.

![Image](https://github.com/ConservationInternational/cplus-plugin/assets/7352963/ff82325f-da0f-46f3-8e11-b0b7ffbba0a1)

**Comment by danangmassandy** [comment]
Implemented via https://github.com/ConservationInternational/cplus-plugin/pull/463
